---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code_quality:
    name: "Code Quality Conrol"

    runs-on: "ubuntu-24.04"

    steps:
      - uses: "actions/checkout@v4"
      - name: Install a specific version
        uses: eifinger/setup-rye@v4
        with:
          version: "latest"
      - name: Rye sync
        run: rye sync
      - name: Rye fmt checking
        run: rye fmt --check
      #   - name: Rye lint
      #     run: rye lint
      - name: Pylint project
        run: rye run pylint src

  tests:
    strategy:
      matrix:
        os: ["ubuntu-24.04", "windows-2022", "macos-15"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    name: "${{ matrix.os }} - Python ${{ matrix.python-version }}"
    runs-on: "${{ matrix.os }}"

    needs:
      - code_quality

    steps:
      - uses: "actions/checkout@v4"
      - name: Install a specific version
        uses: eifinger/setup-rye@v4
        with:
          version: "latest"
      - name: Rye sync
        run: rye sync
      - name: pytest tests
        run: rye test
